/*
 
Auto-generated by Frida. Please modify to match the signature of MessageBoxW.
This stub is currently auto-generated from manpages when available.*
For full API reference, see: https://frida.re/docs/javascript-api/*/

defineHandler({
  onEnter(log, args, state) {
    log('MessageBoxW()');
    log('lpText',args[1]);
    // log('lpText',Memory.readUtf16String(args[1])); //test this
    log('lpCaption',args[2]);
  },

  onLeave(log, retval, state) {
  }
});
